name: Deploy Infrastructure with Pulumi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Pulumi
      run: |
        curl -fsSL https://get.pulumi.com | sh
        export PATH=$PATH:$HOME/.pulumi/bin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Create Key Pair
      run: |
        if [ ! -f my-key.pem ]; then
          aws ec2 create-key-pair --key-name my-key --query 'KeyMaterial' --output text > my-key.pem
          chmod 400 my-key.pem
        else
          echo "Key pair already exists."
        fi

    - name: Install Pulumi dependencies
      run: |
        pip install pulumi pulumi-aws

    - name: Run Pulumi stack
      run: |
        pulumi up --yes