name: Deploy Infrastructure with Pulumi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Pulumi
      run: |
        curl -fsSL https://get.pulumi.com | sh
        export PATH=$PATH:$HOME/.pulumi/bin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Check if Key Pair Exists in AWS
      id: check_keypair
      run: |
        aws ec2 describe-key-pairs --key-name my-key > /dev/null 2>&1 || echo "notfound"

    - name: Create Key Pair if Not Exists
      if: steps.check_keypair.outputs.result == 'notfound'
      run: |
        echo "Key pair not found, creating it..."
        aws ec2 create-key-pair --key-name my-key --query 'KeyMaterial' --output text > my-key.pem
        chmod 400 my-key.pem

    - name: Install Pulumi dependencies
      run: |
        pip install pulumi pulumi-aws

    - name: Login to Pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi login

# Select this stack
    - name: Pulumi stack select
      run: |
        pulumi stack select arifhossaincse22/aws-infra-02/dev

# # Run the program to update the stack
# pulumi up
#     # - name: Pulumi stack select
#     #   run: |
#     #     source venv/bin/activate
#     #     cd aws-infra-01
#     #     pulumi stack select arifhossaincse22/aws-infra-02/dev

    - name: Pulumi up
      run: |
        source venv/bin/activate
        cd aws-infra-01
        pulumi up --yes